### ISSUE TITLE
undefined (reading 'queryTemperatureSensor')

### ISSUE THREAD

**Issue by johannesparty** [senorshaun/homebridge-radiora2#36]
Every hour I get an error like the one below and it causes the bridge process to restart.

```
[11/1/2023, 12:00:36 PM] [RadioRA2] ~HVAC,112,1,76
[11/1/2023, 12:00:36 PM] [RadioRA2] ~HVAC,112,15,24.4
[11/1/2023, 12:00:36 PM] [RadioRA2] [Upstairs] Current Temperature - 24.4
[11/1/2023, 12:01:01 PM] [RadioRA2] ~OUTPUT,47,1,0.00
[11/1/2023, 12:01:01 PM] [RadioRA2] ~OUTPUT,47,29,0
[11/1/2023, 12:01:01 PM] [RadioRA2] ~OUTPUT,47,30,1,0.00
[11/1/2023, 12:01:02 PM] [RadioRA2] ~OUTPUT,49,1,0.00
[11/1/2023, 12:01:02 PM] [RadioRA2] ~OUTPUT,49,29,0
[11/1/2023, 12:01:02 PM] [RadioRA2] ~OUTPUT,49,30,1,0.00
[11/1/2023, 12:01:02 PM] [RadioRA2] ~DEVICE,21,92,9,1
[11/1/2023, 12:01:13 PM] [RadioRA2] ~HVAC,75,1,71
[11/1/2023, 12:01:13 PM] [RadioRA2] ~HVAC,75,15,21.7
[11/1/2023, 12:01:13 PM] [RadioRA2] [Bedroom 1] Current Temperature - 21.7
[11/1/2023, 12:33:42 PM] [RadioRA2] ~HVAC,112,1,75
[11/1/2023, 12:33:42 PM] [RadioRA2] ~HVAC,112,15,23.9
[11/1/2023, 12:33:42 PM] [RadioRA2] [Upstairs] Current Temperature - 23.9

/usr/lib/node_modules/homebridge-radiora2/lib/accessories/temperaturesensor.js:87
            this.radiora2.queryTemperatureSensor(this.config.id);
                          ^
TypeError: Cannot read properties of undefined (reading 'queryTemperatureSensor')
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-radiora2/lib/accessories/temperaturesensor.js:87:27)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
[11/1/2023, 12:33:50 PM] [RadioRA2] Child bridge process ended
[11/1/2023, 12:33:50 PM] [RadioRA2] Process Ended. Code: 1, Signal: null
[11/1/2023, 12:33:57 PM] [RadioRA2] Restarting Process...
[11/1/2023, 12:33:57 PM] [RadioRA2] Launched child bridge with PID 288747
[11/1/2023, 12:33:57 PM] Registering platform 'homebridge-radiora2.RadioRA2'
[11/1/2023, 12:33:57 PM] [RadioRA2] Loaded homebridge-radiora2 v1.7.3 child bridge successfully
[11/1/2023, 12:33:57 PM] Loaded 6 cached accessories from cachedAccessories.0ED8319841AA.
[11/1/2023, 12:33:57 PM] [RadioRA2] Attempting connection to 192.168.5.22...
[11/1/2023, 12:33:57 PM] [RadioRA2] Connecting...
[11/1/2023, 12:33:57 PM] Homebridge v1.6.1 (HAP v0.11.1) (RadioRA2) is running on port 39709.
[11/1/2023, 12:33:57 PM] [RadioRA2] Logged in to RadioRA2 Main Repeater at 192.168.5.22
[11/1/2023, 12:33:57 PM] [RadioRA2] Loaded 0 fan(s)
[11/1/2023, 12:33:57 PM] [RadioRA2] Loaded 0 light(s)
[11/1/2023, 12:33:57 PM] [RadioRA2] Loaded 0 occupancy sensor(s)
[11/1/2023, 12:33:57 PM] [RadioRA2] Loaded 0 keypad(s)
[11/1/2023, 12:33:57 PM] [RadioRA2] Loaded 0 visor control reciever(s)
[11/1/2023, 12:33:57 PM] [RadioRA2] Loaded tempurature sensor 'Living Room'
[11/1/2023, 12:33:57 PM] [RadioRA2] Loaded hvac controller 'Living Room'
[11/1/2023, 12:33:57 PM] [RadioRA2] Loaded tempurature sensor 'Upstairs'
[11/1/2023, 12:33:57 PM] [RadioRA2] Loaded hvac controller 'Upstairs'
[11/1/2023, 12:33:57 PM] [RadioRA2] Loaded tempurature sensor 'Master Bedroom'
[11/1/2023, 12:33:57 PM] [RadioRA2] Loaded hvac controller 'Bedroom 1'
[11/1/2023, 12:33:57 PM] [RadioRA2] Loaded 3 hvac controller(s)
[11/1/2023, 12:33:57 PM] [RadioRA2] Loaded 0 window covering(s)
[11/1/2023, 12:33:57 PM] [RadioRA2] ~HVAC,73,15,23
[11/1/2023, 12:33:57 PM] [RadioRA2] [Living Room] Current Temperature - 23
[11/1/2023, 12:33:57 PM] [RadioRA2] ~HVAC,73,16,13,16
[11/1/2023, 12:33:57 PM] [RadioRA2] [Living Room] Heating setpoint - 13
[11/1/2023, 12:33:57 PM] [RadioRA2] [Living Room] Cooling setpoint - 16
[11/1/2023, 12:33:57 PM] [RadioRA2] ~HVAC,73,3,2
[11/1/2023, 12:33:57 PM] [RadioRA2] [Living Room] Mode set to 1
[11/1/2023, 12:33:58 PM] [RadioRA2] ~HVAC,73,14,0
[11/1/2023, 12:33:58 PM] [RadioRA2] [Living Room] Currently off
[11/1/2023, 12:33:58 PM] [RadioRA2] ~DEVICE,74,1,22,0x00C1BC0D,1,1,04/29/2016 22:33:45
[11/1/2023, 12:33:58 PM] [RadioRA2] ~HVAC,112,15,24
[11/1/2023, 12:33:58 PM] [RadioRA2] [Upstairs] Current Temperature - 24
[11/1/2023, 12:33:58 PM] [RadioRA2] ~HVAC,112,16,13,16
[11/1/2023, 12:33:58 PM] [RadioRA2] [Upstairs] Heating setpoint - 13
[11/1/2023, 12:33:58 PM] [RadioRA2] [Upstairs] Cooling setpoint - 16
[11/1/2023, 12:33:58 PM] [RadioRA2] ~HVAC,112,3,2
[11/1/2023, 12:33:58 PM] [RadioRA2] [Upstairs] Mode set to 1
[11/1/2023, 12:33:58 PM] [RadioRA2] ~HVAC,112,14,0
[11/1/2023, 12:33:58 PM] [RadioRA2] [Upstairs] Currently off
[11/1/2023, 12:33:58 PM] [RadioRA2] ~DEVICE,113,1,22,0x00C514DA,1,1,12/14/2022 23:47:23
[11/1/2023, 12:33:58 PM] [RadioRA2] ~HVAC,75,15,22
[11/1/2023, 12:33:58 PM] [RadioRA2] [Bedroom 1] Current Temperature - 22
[11/1/2023, 12:33:58 PM] [RadioRA2] ~HVAC,75,16,13,26
[11/1/2023, 12:33:58 PM] [RadioRA2] [Bedroom 1] Heating setpoint - 13
[11/1/2023, 12:33:58 PM] [RadioRA2] [Bedroom 1] Cooling setpoint - 26
[11/1/2023, 12:33:58 PM] [RadioRA2] ~HVAC,75,3,2
[11/1/2023, 12:33:58 PM] [RadioRA2] [Bedroom 1] Mode set to 1
[11/1/2023, 12:33:59 PM] [RadioRA2] ~HVAC,75,14,0
[11/1/2023, 12:33:59 PM] [RadioRA2] [Bedroom 1] Currently off
[11/1/2023, 12:33:59 PM] [RadioRA2] ~DEVICE,78,1,22,0x00C49F66,1,1,02/20/2021 00:55:26
```

**Comment by senorshaun** [comment]
good find. I dont have temp sensors so I never tested that out. I just pushed a beta version that may fix it. can you try that out?

**Comment by johannesparty** [comment]
I don't see the beta version.  Either you forgot to push it, or I'm just looking in the wrong place (totally possible).  Thanks.

**Comment by senorshaun** [comment]
using homebridge-config-ui-x, go to the plugin tab, click the wrench next to homebridge-radiora2 then install alternate version. in the drop down select 1.7.4-beta.0

**Comment by johannesparty** [comment]
Ok, running for 3.5 hours and zero instances of the restart, so I think we can say it is fixed (assuming your "beta version" has the fix you want).  Thanks!

**Comment by senorshaun** [comment]
ok I'll close this out and push that to production with the next release
